name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - run: iwr https://win.wasmer.io -useb | iex
      - uses: actions/checkout@v3
      - run: bazel build //...
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://get.wasmer.io -sSfL | sh
      - uses: actions/checkout@v3
      - run: bazel build //...
