name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - run: bazel build //...

  build-windows:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v2
      - run: bazel build //...
